### ISSUE TITLE
Additions to your list

### ISSUE THREAD

**Issue by randomaccess3** [Cugu/awesome-forensics#1]
There's a few additions to your list you might appreciate

Devon Ackerman's Definitive DFIR Compendium Project
https://docs.google.com/spreadsheets/d/1JY-iyw-LEuPCkBAdjorMJhmhGRusN95eLmejWcky7XU/edit#gid=0

http://DFIR.training
and my blog
thisweekin4n6.wordpress.com

Cheers!

**Comment by Cugu** [comment]
I added your suggestions. Thanks a lot!
