### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by lubnafathima** [cugu/awesome-forensics#59]
Hey @cugu 
To help people easily locate the ids
I can correct the alignment of the items in README.md
Kindly assign it to me.

**Comment by cugu** [comment]
Which ids?

**Comment by lubnafathima** [comment]
I means all the items in the README.md

**Comment by cugu** [comment]
Which items do you consider misaligned?

**Comment by lubnafathima** [comment]
In readme.md, I have taken the screenshot of an example
![awesome-forensics](https://user-images.githubusercontent.com/69050759/186449904-16b5fe72-5ae8-4934-bd3f-6f193f132c84.png)

> In tools, you can see that it is not in alphabetical order. So I thought of correcting the alignments
